# Generated by Django 3.2 on 2021-10-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_owner',
            new_name='owner',
        ),
    ]
